modality: single_table
method_params:
  timeout: 60
  compute_quality_score: true
  compute_diagnostic_score: true
  compute_privacy_score: false

compute:
  service: 'gcp'

credentials_filepath: null

instance_jobs:
  - output_destination: 's3://sdgym-benchmark/Debug/Benchmark_Launcher/CONFIG/'
    synthesizers:
      - ColumnSynthesizer
      - GaussianCopulaSynthesizer
    datasets:
      - expedia_hotel_logs
      - fake_hotel_guests
  - output_destination: 's3://sdgym-benchmark/Debug/Benchmark_Launcher/CONFIG/'
    synthesizers:
      - TVAESynthesizer
    datasets:
      - expedia_hotel_logs
      - fake_hotel_guests

