{% set name = 'sdgym' %}
{% set version = '0.4.2.dev0' %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

build:
  number: 0
  noarch: python
  entry_points:
    - sdgym=sdgym.__main__:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - pytest-runner
    - graphviz
    - python >=3.6,<3.9
    - appdirs >=1.1.4,<2
    - boto3 >=1.15.0,<2
    - botocore >=1.20,<2
    - humanfriendly >=8.2,<11
    - numpy >=1.18.0,<2
    - pandas >=1.1,<1.1.5
    - pomegranate >=0.13.4,<0.14.2
    - psutil >=5.7,<6
    - rdt >=0.4.1
    - sdmetrics >=0.3.0
    - sdv >=0.9.0
    - scikit-learn >=0.23,<1
    - tabulate >=0.8.3,<0.9
    - pytorch >=1.4,<2
    - tqdm >=4.14,<5
    - XlsxWriter >=1.2.8,<4
  run:
    - python >=3.6,<3.9
    - appdirs >=1.1.4,<2
    - boto3 >=1.15.0,<2
    - botocore >=1.20,<2
    - humanfriendly >=8.2,<11
    - numpy >=1.18.0,<2
    - pandas >=1.1,<1.1.5
    - pomegranate >=0.13.4,<0.14.2
    - psutil >=5.7,<6
    - rdt >=0.4.1
    - sdmetrics >=0.3.0
    - sdv >=0.9.0
    - scikit-learn >=0.23,<1
    - tabulate >=0.8.3,<0.9
    - pytorch >=1.4,<2
    - tqdm >=4.14,<5
    - XlsxWriter >=1.2.8,<4

about:
  home: "https://github.com/sdv-dev/SDGym"
  license: MIT
  license_family: MIT
  license_file:
  summary: "A framework to benchmark the performance of synthetic data generators for non-temporal tabular data"
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - sdv-dev
