name: Run SDGym Benchmark Manually

on:
  workflow_dispatch:
    inputs:
      modality:
        description: "Benchmark modality"
        required: true
        type: choice
        options:
          - single_table
          - multi_table
      datasets:
        description: "Space-separated datasets, e.g. 'adult alarm'. If not provided, all datasets for the modality will be included."
        required: false
        type: string
      synthesizers:
        description: "Space-separated synthesizers, e.g. 'CTGANSynthesizer TVAESynthesizer'. If not provided, all synthesizers for the modality will be included."
        required: false
        type: string
      num_instances:
        description: "Number of instances"
        required: false
        default: "1"
        type: string
      output_destination:
        description: "Required output destination"
        required: true
        type: string
      timeout:
        description: "Optional timeout in seconds"
        required: false
        type: string

  workflow_call:
    inputs:
      modality:
        required: true
        type: string
      datasets:
        required: false
        type: string
      synthesizers:
        required: false
        type: string
      num_instances:
        required: false
        type: string
        default: "1"
      output_destination:
        required: true
        type: string
      timeout:
        required: false
        type: string
    secrets:
      SDV_ENTERPRISE_USERNAME:
        required: true
      SDV_ENTERPRISE_LICENSE_KEY:
        required: true
      GCP_SERVICE_ACCOUNT_JSON:
        required: true
      GCP_PROJECT_ID:
        required: true
      GCP_ZONE:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  run:
    uses: ./.github/workflows/_run_benchmark.yml
    with:
      modality: ${{ inputs.modality }}
      datasets: ${{ inputs.datasets }}
      synthesizers: ${{ inputs.synthesizers }}
      num_instances: ${{ inputs.num_instances }}
      output_destination: ${{ inputs.output_destination }}
      timeout: ${{ inputs.timeout }}
    secrets:
      SDV_ENTERPRISE_USERNAME: ${{ secrets.SDV_ENTERPRISE_USERNAME }}
      SDV_ENTERPRISE_LICENSE_KEY: ${{ secrets.SDV_ENTERPRISE_LICENSE_KEY }}
      GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_ZONE: ${{ secrets.GCP_ZONE }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
