name: Run SDGym Benchmark from YAML Config file

on:
  workflow_dispatch:
    inputs:
      config_filepath:
        description: "Path to the benchmark YAML file in the selected branch"
        required: true
        type: string

jobs:
  run:
    uses: ./.github/workflows/_run_benchmark.yml
    with:
      config_filepath: ${{ inputs.config_filepath }}
    secrets:
      SDV_ENTERPRISE_USERNAME: ${{ secrets.SDV_ENTERPRISE_USERNAME }}
      SDV_ENTERPRISE_LICENSE_KEY: ${{ secrets.SDV_ENTERPRISE_LICENSE_KEY }}
      GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_ZONE: ${{ secrets.GCP_ZONE }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
